import org.apache.hadoop.conf.Configuration;
import edu.duke.starfish.profile.profiler.loaders.tasks.*;

/**
 * Read the stdouts generated by containers;
 * Generate task profiles;
 * @author WangYu
 */

public class ExecuteProfile {

	private String appId = "";
	private String filePath = "/home/hadoop/starfish/starfish/results/";
	private Configuration conf;

	public ExecuteProfile(String appid) {
		appId = appid;
		String seperator = System.getProperty("file.seperator");
		filePath = filePath + "application_" + appId;
	}

	public void setFilePath(String path) {
		filePath = path;
	}

	public void loadProfile() {
		conf = new Configuration();
		File[] files = filePath.listFiles();

		File oneFile = new File(files[3], "stdout");
		System.out.println(oneFile.getAbsolutePath());
	}
	
	public static void main(String[] args) {

		ExecuteProfile executeProfile = new ExecuteProfile(args[1]);
		executeProfile.loadProfile();

	}

}