// package edu.duke.starfish.profile.profiler.loaders.tasks;

import org.apache.hadoop.conf.Configuration;
import edu.duke.starfish.profile.profileinfo.execution.profile.*;
import edu.duke.starfish.profile.profiler.loaders.tasks.*;

import java.io.*;

/**
 * Read the stdouts generated by containers;
 * Generate task profiles;
 * @author WangYu
 */

public class ExecuteProfile {

	private String appId = "";
	private String filePath = "/home/hadoop/starfish/starfish/results/";
	private Configuration conf;

	public ExecuteProfile(String appid) {
		appId = appid;
		String seperator = System.getProperty("file.seperator");
		filePath = filePath + "application_" + appId;
	}

	public void setFilePath(String path) {
		filePath = path;
	}

	public void loadProfile() {
		Configuration conf = new Configuration();
		conf.addResource("/home/hadoop/hadoop-2.2.0/etc/hadoop/mapred-site.xml");
		File files = new File(filePath);
		File[] containers = files.listFiles();

		File oneFile = new File(containers[3], "stdout");
		MRMapProfile profile = new MRMapProfile(oneFile.getName());
		MRMapProfileLoader loader = new MRMapProfileLoader(profile, conf, oneFile.getAbsolutePath());
		try{
			MRTaskProfile taskProfile = (MRTaskProfile)loader.getProfile();
			if (loader.loadExecutionProfile(taskProfile)) {
				taskProfile.printProfile(System.out);
			}
			else {
				System.out.println("false");
			}
		}catch (Exception e) {
			System.out.println(1 + e.getMessage());
		}

		oneFile = new File("/home/hadoop/starfish/starfish/results/application_1397147117653_0137/container_1397147117653_0137_01_000024/stdout");
		MRReduceProfile reduceProfile = new MRReduceProfile(oneFile.getName());
		MRReduceProfileLoader reduceLoader = new MRReduceProfileLoader(reduceProfile, conf, oneFile.getAbsolutePath());
		try {
			MRTaskProfile taskProfile = (MRTaskProfile)reduceLoader.getProfile();
			if (reduceLoader.loadExecutionProfile(taskProfile)) {
				taskProfile.printProfile(System.out);
			}
		}
		catch (Exception e) {
			System.out.println(2 + e.getMessage());
		}
	}
	
	public static void main(String[] args) {
		// System.out.println("dkff");
		ExecuteProfile executeProfile = new ExecuteProfile(args[0]);
		executeProfile.loadProfile();

		System.out.println("dkf");

	}

}